apiVersion: apps/v1
kind: Deployment

metadata:
  name: posts-api
  namespace: backend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: posts-api

  template:
    metadata:
      labels:
        app: posts-api

    spec:
      containers:
        - name: posts-api

          image: 152924643387.dkr.ecr.us-east-1.amazonaws.com/posts-api:latest

          ports:
            - containerPort: 5000

          env:
            - name: PORT
              value: "5000"

            - name: MONGO_URI
              value: mongodb://admin:password@mongodb:27017/postsdb?authSource=admin