apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: mongodb
  namespace: backend

spec:
  serviceName: mongodb
  replicas: 3

  selector:
    matchLabels:
      app: mongodb

  volumeClaimTemplates:
    - metadata:
        name: mongo-data

      spec:
        accessModes:
          - ReadWriteOnce

        storageClassName: gp2

        resources:
          requests:
            storage: 5Gi

  template:
    metadata:
      labels:
        app: mongodb

    spec:
      containers:
        - name: mongodb
          image: mongo:7

          command:
            - mongod
            - "--replSet"
            - "rs0"
            - "--bind_ip_all"

          ports:
            - containerPort: 27017

          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: username

            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: password

          envFrom:
            - configMapRef:
                name: mongodb-config

          resources:
            requests:
              cpu: 200m
              memory: 256Mi

            limits:
              cpu: 500m
              memory: 512Mi

          volumeMounts:
            - name: mongo-data
              mountPath: /data/db